# Changes here will be overwritten by Copier
_commit: v0.1.1
_src_path: git@github.com:zauberzeug/nicegui-template.git
module_name: basekit_ros
project_description: todo
project_name: basekit_ros
python_versions:
- '3.11'
- '3.12'
use_poetry: false
use_precommit: true
