version: "3.8"

services:
  basekit:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: basekit_ros:latest
    network_mode: host # Required for ROS2 communication
    privileged: true # Required for hardware access
    devices:
      - /dev/ttyTHS0:/dev/ttyTHS0 # Field Friend serial port
      - /dev/ttyACM0:/dev/ttyACM0 # GNSS receiver (USB ACM)
      - /dev/video0:/dev/video0 # Camera main video stream
      - /dev/video1:/dev/video1 # Camera metadata stream
      - /dev/media1:/dev/media1 # Camera media controller
    volumes:
      - /dev:/dev # Access to all devices (alternative to individual mappings)
      - ~/.ros:/root/.ros # For ROS logs
    environment:
      - ROS_DOMAIN_ID=0 # Default ROS domain
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Using CycloneDDS

    # Source and launch the main launch file
    command: bash -c "source /opt/ros/humble/setup.bash && source /workspace/install/setup.bash && ros2 launch basekit_launch camera_system.launch.py"
    restart: unless-stopped
