/**:
  ros__parameters:
    ## Sensor standard deviation [x,y,z] (optional)
    ## This value is used to override the covariance matrix in nav_msgs/Odometry
    ## Important: Make sure the values provided are in decimal points, or else might give error in execution
    pose_stddev: [0.1, 0.1, 0.0, 0.0, 0.0, 0.1] # [m]
    twist_stddev: [0.01, 0.0, 0.0, 0.0, 0.0, 0.01] # [m/s]
    publish_tf: False

    read_data:
      list:
        - time
        - linear_speed
        - angular_speed
        - yaxis_end_l_active
        - yaxis_end_r_active
        - yaxis_motor_actual_position
        - yaxis_status_target_reached
        - yaxis_motor_status_fault
        - yaxis_ctrl_enable
        - zaxis_end_t_active
        - zaxis_end_b_active
        - zaxis_motor_actual_position
        - zaxis_status_target_reached
        - zaxis_motor_status_fault
        - estop1_level
        - estop2_level
        - battery_status_level
        - bumper_front_top_level
        - bumper_front_bottom_level
        - bumper_back_level
        - imu_cal_gyr
        - imu_quat_w
        - imu_quat_x
        - imu_quat_y
        - imu_quat_z
        - rdyp_level
        - vdp_level
        - heap

      time:
        type: double
        default: 0.0
      linear_speed:
        type: double
        default: 0.0
      angular_speed:
        type: double
        default: 0.0
      yaxis_end_l_active:
        type: bool
        default: False
      yaxis_end_r_active:
        type: bool
        default: False
      yaxis_motor_actual_position:
        type: double
        default: 0.0
      yaxis_status_target_reached:
        type: bool
        default: False
      yaxis_motor_status_fault:
        type: bool
        default: False
      yaxis_ctrl_enable:
        type: bool
        default: False
      zaxis_end_t_active:
        type: bool
        default: False
      zaxis_end_b_active:
        type: bool
        default: False
      zaxis_motor_actual_position:
        type: double
        default: 0.0
      zaxis_status_target_reached:
        type: bool
        default: False
      zaxis_motor_status_fault:
        type: bool
        default: False
      estop1_level:
        type: bool
        default: False
      estop2_level:
        type: bool
        default: False
      battery_status_level:
        type: bool
        default: False
      bumper_front_top_level:
        type: bool
        default: False
      bumper_front_bottom_level:
        type: bool
        default: False
      bumper_back_level:
        type: bool
        default: False
      imu_cal_gyr:
        type: double
        default: 0.0
      imu_quat_w:
        type: double
        default: 0.0
      imu_quat_x:
        type: double
        default: 0.0
      imu_quat_y:
        type: double
        default: 0.0
      imu_quat_z:
        type: double
        default: 0.0
      rdyp_level:
        type: bool
        default: False
      vdp_level:
        type: bool
        default: False
      heap:
        type: double
        default: 0.0
