name: Run Tests

on: [push]

jobs:
  code-checks:
    strategy:
      matrix:
        tools:
          # TODO: make sure mypy and pylint get all imports
          - command: "mypy ./basekit_driver/basekit_driver --non-interactive --install-types --ignore-missing-imports"
          - command: "pylint --disable=import-error ./basekit_driver/basekit_driver"
          - command: "ruff check ./basekit_driver/basekit_driver"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: install dependencies
        run: pip install -r requirements-dev.txt
      - name: ${{ matrix.tools.command }}
        run: ${{ matrix.tools.command }}
